# fly.toml app configuration file generated for phonebook-practice-fix on 2024-05-04T23:49:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-practice-fix'
primary_region = 'arn'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
